# Q1

In [1]:
import numpy as np 
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
np.reshape(a, [3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q2

In [22]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
cond = a % 2 != 0
a[cond] = -1

# Q3

In [23]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater = np.where(x > y)[0]
equal = np.where(x == y)[0]
greater

array([1, 2, 4, 5, 6, 7, 8, 9])

# Q4

In [11]:
a = np.arange(100).reshape(5,-1)
arr = a[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

# Additional

In [25]:
np.random.randint(low=30, high=40, size=10)

array([34, 32, 34, 39, 30, 38, 39, 33, 35, 31])

In [35]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10], [4, 5, 6], [1, 2, 3]])

C = A + B
E = A - B

In [45]:
C_trans

array([[ 8, 10, 12],
       [ 8, 10, 13],
       [ 8, 10, 13]])

In [48]:
sumrowC

array([31, 30, 31])

In [36]:
sumA = np.sum(A)
sumcolB = np.sum(B, axis=0)
sumrowC = np.sum(C, axis=1)

In [37]:
D = np.dot(A, B)

In [38]:
C_sort = np.sort(C.flatten()).reshape(C.shape)

In [44]:
C_trans = C_sort.T